export default [
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        // Browser globals
        document: "readonly",
        window: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        fetch: "readonly",
        Blob: "readonly",
        File: "readonly",
        FileReader: "readonly",
        URL: "readonly",
        HTMLCanvasElement: "readonly",
        WebGLRenderingContext: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        crypto: "readonly",
        // Web Audio API
        AudioContext: "readonly",
        MediaStream: "readonly",
        // Three.js
        THREE: "readonly",
        // Custom globals
        API_BASE: "readonly",
        CLIENT_VERSION: "readonly",
        CLIENT_BUILD_DATE: "readonly",
        JARVIS_SERVER_URL: "readonly",
        // JARVIS UI globals
        toggleTranscriptPath: "writable",
        toggleTranscriptFullscreen: "writable",
        audioContext: "writable",
        mediaStreamSource: "writable",
        scriptProcessor: "writable",
        streamingInterval: "writable",
        lastTranscript: "writable",
        serverStatusInterval: "writable",
        checkServerStatus: "writable",
        startListening: "writable",
        stopListening: "writable",
        audioSource: "writable",
        isListening: "writable",
        currentMode: "writable",
        // NeuroGraph globals
        GraphViewer: "writable",
        NeuroGraph: "writable",
        jarvisGraph: "writable",
        userGraph: "writable",
        setupPanelToggles: "writable",
        setupGlobalSearchInput: "writable",
        populateGlobalTypeFilters: "writable",
        initDualGraphs: "writable",
        setupCollapsibleFilters: "writable",
        setupSearchInputs: "writable",
        setupFilterButtons: "writable",
        setupFilterToggle: "writable",
        setupSyncButtons: "writable",
        setupFilterToggle: "writable",
        updateStats: "writable",
        // Helper functions
        formatTime: "writable",
        formatDate: "writable",
        formatDuration: "writable",
        calculateStats: "writable",
        clearCanvas: "writable",
        drawSphere: "writable",
        drawRing: "writable",
        drawHelix: "writable",
        drawSynapse: "writable",
        drawNodeLabel: "writable",
        randomColor: "writable",
        resizeCanvas: "writable",
        loadGraphData: "writable",
        renderGraph: "writable",
        checkNodeVisibility: "writable",
        updateNodePositions: "writable",
        createGraphScene: "writable",
        setupInteractions: "writable",
        setSearchTerm: "writable",
        clearSelection: "writable",
        randomPulse: "writable",
        toggleNeuralNetwork: "writable",
        updateNeuralNetwork: "writable",
      },
    },
    rules: {
      "no-redeclare": "error",
      "no-duplicate-imports": "error",
      "no-unreachable": "error",
      "semi": ["error", "always"],
      "no-undef": "off", // We handle globals explicitly above
      "no-unused-vars": ["off"], // Some unused vars are intentional
      "no-console": "off",
      "indent": ["error", 2],
      "quotes": ["error", "single"],
      "eqeqeq": ["error", "smart"],
      "curly": ["error", "all"],
      "no-empty": "error",
      "no-fallthrough": "error",
    },
  },
];
